version: '3.8'

services:
  benchmark:
    build: .
    mem_limit: 2g
    memswap_limit: 2g
    ports:
      - "3000-3999:3000-3999"
    networks:
      - bench_net_1
      - bench_net_2
      - bench_net_3
      - bench_net_4
      - bench_net_5
      - bench_net_6
      - bench_net_7
      - bench_net_8
      - bench_net_9
      - bench_net_10

networks:
  bench_net_1:
  bench_net_2:
  bench_net_3:
  bench_net_4:
  bench_net_5:
  bench_net_6:
  bench_net_7:
  bench_net_8:
  bench_net_9:
  bench_net_10: